name: BytesandBotPlugin
main: bytesandbots.custom.customrules.Main
version: 1.0
api-version: 1.19
author: Fernando
commands:

   punish:
      description: OP can punish player.
   unpunish:
      description: OP can unpunish player.
   sethome:
      description: Set your home
   homes:
      description: See all your homes
   home:
      description: Teleport to a home
   breakable:
      description: OP can break any block
   survival:
      description: Puts you in survival
   creative:
      description: Puts you in creative