name: BytesandBotPlugin
main: bytesandbots.custom.customrules.Main
version: "1"
api-version: 1.19
author: Fernando
commands: 
  Curryisdelicous: 
    description: Curry's custom command
  hummus: 
    description: CungDo's custom command
  punish: 
    description: OP can punish player.
  unpunish: 
    description: OP can unpunish player.
  sethome: 
    description: Set your home
  homes: 
    description: See all your homes
  home: 
    description: Teleport to a home
  breakable: 
    description: OP can break any block
  survival: 
    description: Puts you in survival
  creative: 
    description: Puts you in creative
  pvp: 
    description: Puts you in pvp
  mmo:
    description: Puts you in MMO mode, saves your inventory
  unmmo:
    description: sends you back to the normal creative world. Saves your mmo inventory
  createTrader:
    description: make a trader